# Generated by Django 4.2 on 2024-08-01 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('A', 'Agua'), ('F', 'Fuego'), ('E', 'Eléctrico'), ('P', 'Planta'), ('L', 'Lagartija'), ('T', 'Tierra')], max_length=30),
        ),
    ]
